Application\Entity\User:
  repositoryClass: Application\Repository\UserRepository
  type: entity
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    password:
      type: string
      length: 32
    username:
      type: string
      length: 128
  oneToOne:
    role:
      targetEntity: \Application\Entity\Role
      inversedBy: user
      joinColumn:
        name: role_id
        referencedColumnName: id
  indexes:
    search_idx:
      columns: username